#pragma once

#define RXPORT 8314

#define NETBUFF_SAMPLES 64
#define NETBUFF_BYTES (NETBUFF_SAMPLES * 2)

#define RX_QUEUE_SIZE 2

#define RINGBUFF_SAMPLES (NETBUFF_SAMPLES * RX_QUEUE_SIZE * 4)
#define RINGBUFF_BYTES (RINGBUFF_SAMPLES * 2)