#pragma once

#define BLOCK_SIZE 64
#define MAX_RX_QUEUE_SIZE 32

#define NETBUFF_SAMPLES (BLOCK_SIZE / 2)

#define RINGBUFF_SAMPLES (NETBUFF_SAMPLES * MAX_RX_QUEUE_SIZE * 2)

#define APP_PORT_NUMBER 43000